name: photo_curator
description: Flutter-based on-device travel photo curation system
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI and state management
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  
  # Image processing and gallery
  photo_manager: ^2.7.1
  image: ^4.0.17
  
  # TensorFlow Lite
  tflite_flutter: ^0.9.0
  
  # File and path handling
  path_provider: ^2.0.15
  path: ^1.8.3
  
  # Utilities
  permission_handler: ^10.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/